### ISSUE TITLE
byline 4.1.1 deprecated

### ISSUE THREAD

**Issue by flootr** [cozy/cozy-ical#25]
After `npm i cozy-ical`:
`npm WARN deprecated byline@4.1.1: critical bug fixed in v4.2.0`

I would appreciate an update to the current version.

**Comment by frankrousseau** [comment]
Thank you @flootr for the bug report. Can you contribute to the NPM manifest and put the right version in it?

**Comment by flootr** [comment]
https://github.com/cozy/cozy-ical/commit/d2219fe327503639af802866227ec43af14c6184
:)
