### ISSUE TITLE
Parsing error when timezone label contains :

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-ical#47]
A user get errors trying to import an ICS file from Outlook: lots of dates are invalid. We are unable to parse them because the timezone label contains a `:`: `DTEND;TZID="(UTC+01:00) Brussels, Copenhagen, Madrid, Paris":20160308T230000`.

**Comment by poupotte** [comment]
@clochix , this issue should be fixed in new cozy-ical version (1.1.19). Do you have any news from  user ?

**Comment by clochix** [comment]
This won't be available to users until we publish new versions using cozy-ical@1.1.19 of the applications using cozy-ical (calendar, konnectors, sync…)

**Comment by frankrousseau** [comment]
@clochix Can you upgrade cozy-ical in all these apps?

**Comment by clochix** [comment]
Well, looks like @aenario did the fix two days ago, but only Sync has been published, the fix is on the development branch of Calendar and Konnectors.

**Comment by poupotte** [comment]
Calendar and Konnectors are now published with cozy-ical@1.1.19. 
So, this issue should be fixed. 
@clochix , do you have some news from the user ?

**Comment by clochix** [comment]
I just noticed the user, waiting for its feedback.

**Comment by clochix** [comment]
The user that reported this issue don't use Cozy anymore, so let's close this.
